# Generated by Django 3.2.10 on 2023-04-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_nombre', models.CharField(max_length=100)),
                ('categoria_descripcion', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
