# Generated by Django 3.2 on 2023-04-07 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiblog', '0002_alter_blog_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='group_service',
            new_name='category',
        ),
    ]
