# Generated by Django 3.2 on 2023-04-08 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiblog', '0003_rename_group_service_blog_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
    ]
