# Generated by Django 3.2 on 2023-04-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiblog', '0004_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.CharField(max_length=70, unique=True, verbose_name='Descripción'),
        ),
    ]
